-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."student_group_metrics" add column "broker_login" text
--  not null;
