-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE smart_plug_tag (
--     id SERIAL PRIMARY KEY,
--     smart_plug_id INTEGER,
--     path LTREE
-- );
