version: '3.6'
services:
  timescale:
    image: timescale/timescaledb:latest-pg12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    command:
    - postgres
    - -c
    - "shared_preload_libraries=timescaledb"
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql:Z
  graphql-engine:
    image: hasura/graphql-engine:v2.0.1.cli-migrations-v3
    ports:
    - "8080:8080"
    depends_on:
    - "timescale"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@timescale:5432/poli_lab
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    volumes:
    - ./migrations:/hasura-migrations:Z
    - ./metadata:/hasura-metadata:Z
volumes:
  db_data:
